<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <meta charset="utf-8">
    <title>Employee Dashboard</title>
    <meta name="description" content="This was generated by the Codeply editor and responsive design playground." />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="generator" content="Codeply">

	<!-- Hosted Bootstrap 4 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.1/animate.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" />
    
    <!-- site specific styling -->
    <link rel="stylesheet" href="./css/styles.css" />
    
    <!-- font awesome -->
    <link href="./font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    
    <!-- jQuery DataTable -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.11/css/jquery.dataTables.min.css" />
    
</head>
<body class="bg-faded">
 
<nav id="topNav" class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <button class="navbar-toggler hidden-md-up pull-right" type="button" data-toggle="collapse" data-target="#collapsingNavbar">
            ☰
        </button>

        <a class="navbar-brand page-scroll" href="getEmployeeData.do">Employee Dashboard</a>

        <div class="collapse navbar-toggleable-sm" id="collapsingNavbar">
            <ul class="nav navbar-nav">
            	<li class="nav-item">
                    <a class="nav-link page-scroll" href="#one">GUI</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link page-scroll" href="#two">Analytics</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link page-scroll" href="#allData">Reports</a>
                </li>
            </ul>

            <ul class="nav navbar-nav pull-xs-right">
                <li class="nav-item">
                    <a class="nav-link page-scroll" data-toggle="modal" href="#aboutModal">About</a>
                </li>
            </ul>
        </div>
    </div><!-- .container -->
</nav>

<c:choose>
	<c:when test="${!empty empData}">
	<section id="two">	
		<div class="container wow fadeInUp">
			<div class="row">
				<div class="col-lg-12">	
				<table id="allData" class="display compact" cellspacing="0" width="100%">
					<thead>
						<tr>
						<c:forEach var="column" items="${empHeaders}">
							<th>${column}</th>
						</c:forEach>	
						</tr>
					</thead>
					<tbody>
						<c:forEach var="row" items="${empData}">
						<tr>
							<c:forEach var="value" items="${row}">
								<td>${value}</td>
							</c:forEach>
						</tr>
						</c:forEach>
					</tbody>
				</table>
				</div>
			</div>
		</div><!-- /.container -->
	</section><!-- /#two -->
	</c:when>
	<c:otherwise>	
	<section id="one">
		<div class="container wow fadeInUp">
			<div class="row">
				<div class="col-lg-8">
				<form action="getEmployeeData.do" method="POST">
					<div class="input-group input-group-lg">
						<span class="input-group-btn">
        					<button class="btn btn-secondary" type="submit">Go!</button>
      					</span>
  						<input type="text" name="query" class="form-control" placeholder="Search by Employee Last Name" aria-describedby="sizing-addon1">
					</div>
				</form>			
				</div><!-- /.col-lg-8 -->
				<div class="col-lg-4">
				<form action="getEmployeeData.do" method="POST">
					<div class="dropdown">
  					<button name="employee" class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Employees</button>
  						<div class="dropdown-menu" aria-labelledby="dropdownMenu1">
    					<c:forEach items="${employees}" var="employee">
    						<a class="dropdown-item" href="getEmployeeData.do?query=${employee.lastName}">${employee.lastName}, ${employee.firstName}</a>
						</c:forEach>
  						</div>
					</div>
				</form>
				</div><!-- .col-lg-4 -->
			</div><!-- /.row -->
			
			<hr>
			
			<div class="col-lg-12">	
				<div class="row">
					<div class="col-md-3">
						<canvas id="genderBarChart" width="250" height="300"></canvas>
					</div><!-- /.col-md-3 -->
				
					<div class="col-md-3">
						<canvas id="salaryBarChart" width="250" height="300"></canvas>
					</div><!-- /.col-md-3 -->
				
					<div class="col-md-6">
						<canvas id="departmentBarChart" width="500" height="300"></canvas>
					</div><!-- /.col-md-6 -->
				</div><!-- /.row -->
			</div><!--  /.col-lg-12 -->
			
		</div><!-- /.container wow fadeInUp -->
	</section>
	<hr>
	</c:otherwise>
</c:choose>

<footer>
	<div class="row">
		<div class="col-lg-12">
			<p class="text-xs-center"><a href="http://www.chrisriouxdevelopment.com" target="_blank">Chris Rioux Development</a> &copy; 2016</p>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6 col-md-offset-3" style="text-align:center">
			<a href="https://twitter.com/chrisrioux_" target="_blank"><i class="fa fa-twitter fa-2x"></i></a>&nbsp;&nbsp;
			<a href="https://www.linkedin.com/in/chris-rioux-b500569a" target="_blank"><i class="fa fa-linkedin fa-2x"></i></a>&nbsp;&nbsp;
			<a href="https://github.com/chrisrioux2" target="_blank"><i class="fa fa-github fa-2x"></i></a>
			</br>
      	</div>
	</div>
</footer>

<!-- Modals -->
<div id="aboutModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
            <div class="card card-block text-xs-center">
		            <div class="card card-block text-xs-center">
		                <h4 class="card-header">Chris Rioux</h4>
						<p class="text-xs-center">Full Stack Java Web Development. Visit My<a href="http://www.chrisriouxdevelopment.com" target="_blank"> Site!</p> 
						<a href="https://twitter.com/chrisrioux_" target="_blank" class="btn btn-primary-outline"><i class="fa fa-twitter fa-fw"></i>&nbsp;&nbsp;Twitter</a>
	                    <a href="https://github.com/chrisrioux2" target="_blank" class="btn btn-primary-outline"><i class="fa fa-github-alt fa-fw"></i>&nbsp;&nbsp;Github</a>
	                    <a href="https://www.linkedin.com/in/chris-rioux-b500569a" target="_blank" class="btn btn-primary-outline"><i class="fa fa-linkedin fa-fw"></i>&nbsp;&nbsp;Linkedin</a>
						<p class="text-xs-center"> </p>
					<div class="card-footer text-muted">
					<img class="card-img-bottom" src="./img/smallestPic.jpg" alt="Card image cap">
					<p class="text-xs-center"> </p>
					<button class="btn btn-primary center-block" data-dismiss="modal" aria-hidden="true"> OK </button>
		            </div>
		       	</div>
            </div>
        	</div>
    	</div>
	</div>
</div><!-- /#aboutModal -->

    <!--scripts loaded here-->    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.js"></script>
    
    <script src="js/scripts.js"></script>
    
    <!-- jQuery DataTable -->
    <script src="https://cdn.datatables.net/1.10.11/js/jquery.dataTables.min.js"></script>
    
    <script>
    	$(document).ready(function() {
        	$('#allData').DataTable();
    	} );
    </script>
    
    <!-- ChartJS -->
    <script src="js/Chart.js-master/Chart.js"></script>
    
    <script>
    // gender counts chart
    var ctx = document.getElementById("genderBarChart").getContext("2d");
		
    	<c:set var="genderCount" value="${demographics.genderCount}"/>
		var genderBarData = {
    		labels: [<c:forEach var="gender" items="${genderCount.keySet()}">"${gender}", </c:forEach>],
    		datasets: [
     			{
       				label: "Gender Dataset",
            		fillColor: "rgba(220,220,220,0.5)",
            		strokeColor: "rgba(220,220,220,0.8)",
            		highlightFill: "rgba(220,220,220,0.75)",
            		highlightStroke: "rgba(220,220,220,1)",
            		data: [<c:forEach var="genderCount" items="${genderCount.values()}">"${genderCount}", </c:forEach>]
        		}
    		]
		};
		
		var genderBarChart = new Chart(ctx).Bar(genderBarData);
		
	// salary totals by gender chart
    var ctx = document.getElementById("salaryBarChart").getContext("2d");
		
		var salaryBarData = {
    		labels: ["Male Total", "Female Total"],
    		datasets: [
     			{
       				label: "Salary Dataset",
       				fillColor: "rgba(151,187,205,0.5)",
            		strokeColor: "rgba(151,187,205,0.8)",
            		highlightFill: "rgba(151,187,205,0.75)",
            		highlightStroke: "rgba(151,187,205,1)",
            		// format as USD
            		data: [235000, 560000]
        		}
    		]
		};
		
		var salaryBarChart = new Chart(ctx).Bar(salaryBarData);
		
	// employee count by department chart
    var ctx = document.getElementById("departmentBarChart").getContext("2d");
		
		var departmentBarData = {
    		labels: ["Dept 1", "Dept 2", "Dept 3", "Dept 4", "Dept 5", "Dept 6"],
    		datasets: [
     			{
       				label: "Department Dataset",
       				fillColor: "rgba(251,187,205,0.5)",
            		strokeColor: "rgba(251,187,205,0.8)",
            		highlightFill: "rgba(251,187,205,0.75)",
            		highlightStroke: "rgba(251,187,205,1)",
            		data: [23, 50, 9, 56, 12, 100]
        		}
    		]
		};
		
		var departmentBarChart = new Chart(ctx).Bar(departmentBarData);
    </script>
    
  </body>
</html>